In [1]:
import pandas as pd
trainDF = pd.DataFrame.from_csv('train.csv')
testDF = pd.DataFrame.from_csv('test.csv')
print (trainDF)

           Race Gender  Year       JobType
41519  Minority    Men  2007     Unskilled
54085     White    Men  2015     Unskilled
25059  Minority    Men  2007  Semi-Skilled
11908  Minority  Women  2015  Semi-Skilled
10850     White    Men  2015       Skilled
63088     White    Men  2015  Semi-Skilled
4990      White    Men  2007       Skilled
21374  Minority    Men  2007     Unskilled
39999  Minority    Men  2007     Unskilled
76321     White  Women  2007     Unskilled
21411  Minority    Men  2007     Unskilled
5872   Minority  Women  2015       Skilled
49823     White    Men  2007     Unskilled
54832     White    Men  2015     Unskilled
43023  Minority  Women  2007     Unskilled
14592     White  Women  2015       Skilled
53878     White    Men  2015     Unskilled
36578     White  Women  2007  Semi-Skilled
12887  Minority  Women  2015  Semi-Skilled
7681      White  Women  2007       Skilled
81908     White  Women  2015     Unskilled
76403     White  Women  2007     Unskilled
11544     W

In [2]:
from sklearn import tree
import numpy as np
from sklearn.feature_extraction import FeatureHasher
data = trainDF.drop('JobType',axis=1)
dataTest = testDF.drop('JobType',axis=1)

target = trainDF.drop('Race',axis=1)
target = target.drop('Gender',axis=1)
target = target.drop('Year',axis=1)
target = target.replace(['Skilled','Semi-Skilled','Unskilled'],[0,1,2])
target = target.as_matrix()

data = data.replace(['Men','Women','Minority','White'],[0,1,0,1])
dataTest = dataTest.replace(['Men','Women','Minority','White'],[0,1,0,1])

print (data)
targetTest = testDF.drop('Race',axis=1)
targetTest = targetTest.drop('Gender',axis=1)
targetTest = targetTest.drop('Year',axis=1)
targetTest = targetTest.replace(['Skilled','Semi-Skilled','Unskilled'],[0,1,2])
targetTest = targetTest.as_matrix()

       Race  Gender  Year
41519     0       0  2007
54085     1       0  2015
25059     0       0  2007
11908     0       1  2015
10850     1       0  2015
63088     1       0  2015
4990      1       0  2007
21374     0       0  2007
39999     0       0  2007
76321     1       1  2007
21411     0       0  2007
5872      0       1  2015
49823     1       0  2007
54832     1       0  2015
43023     0       1  2007
14592     1       1  2015
53878     1       0  2015
36578     1       1  2007
12887     0       1  2015
7681      1       1  2007
81908     1       1  2015
76403     1       1  2007
11544     1       0  2015
1999      1       0  2015
13368     1       1  2015
47305     1       1  2015
55531     1       0  2007
63344     1       0  2015
24198     1       0  2007
893       1       0  2007
...     ...     ...   ...
25712     1       1  2007
44931     1       1  2015
38439     1       1  2007
81641     1       1  2015
47045     0       0  2015
25565     0       0  2007
13731     0 

In [15]:
import sklearn.datasets as datasets
from sklearn.neighbors import KNeighborsClassifier
target = target.ravel()
targetTest = targetTest.ravel()
print (target)
# target = target.as_matrix()
iris = datasets.load_iris()
print (type(iris.target))
k = 3
knn = KNeighborsClassifier(n_neighbors=k)
knn.fit(data,target)

targetTest = knn.predict(dataTest)
print("Accuracy of KNN test set:", knn.score(dataTest, targetTest))

[2 2 1 ..., 1 1 1]
<class 'numpy.ndarray'>
Accuracy of KNN test set: 1.0


In [7]:
from IPython.display import Image  
import pydotplus 
dtc = tree.DecisionTreeClassifier()
# dfOnlySkilled = trainDF[trainDF.JobType != 'Unskilled']
dataTrain = trainDF.drop('JobType',axis=1)
dataTrain = dataTrain.drop('Year',axis=1)
dataTrain = dataTrain.replace(['Men','Women','Minority','White'],[0,1,0,1])
dataTrain = dataTrain.as_matrix()

# testDFOnlySkilled = testDF[testDF.JobType != 'Unskilled']
dataTest = testDF.drop('JobType',axis=1)
dataTest = dataTest.drop('Year',axis=1)
dataTest = dataTest.replace(['Men','Women','Minority','White'],[0,1,0,1])
dataTest = dataTest.as_matrix()

# dfOnlySkilled = trainDF[trainDF.JobType != 'Unskilled']
targetTrain = trainDF.drop('Gender',axis=1)
targetTrain = targetTrain.drop('Race',axis=1)
targetTrain = targetTrain.drop('Year',axis=1)
targetTrain = targetTrain.replace(['Skilled','Semi-Skilled','Unskilled'],[0,1,2])
targetTrain = targetTrain.as_matrix()

# testDFOnlySkilled = testDF[testDF.JobType != 'Unskilled']
targetTest = testDF.drop('Gender',axis=1)
targetTest = targetTest.drop('Race',axis=1)
targetTest = targetTest.drop('Year',axis=1)
targetTest = targetTest.replace(['Skilled','Semi-Skilled','Unskilled'],[0,1,2])
targetTest = targetTest.as_matrix()

targetTest = (targetTest.ravel())
targetTrain = targetTrain.ravel()
print (dataTest)
print (targetTrain.shape)

dtc.fit(dataTrain, targetTrain)
y_pred_test = dtc.predict(dataTest)
print('DT accuracy on test data: ', dtc.score(dataTest, targetTest))
y_pred_train = dtc.predict(dataTest)
print('DT accuracy on training data: ', dtc.score(dataTrain, targetTrain))


dot_data = tree.export_graphviz(dtc,out_file='treeAll.dot',feature_names=['Race','Gender'],  
                         class_names=['Skilled','Semi-Skilled','Unskilled'],
                         filled=True)  



[[1 0]
 [1 0]
 [1 1]
 ..., 
 [1 1]
 [0 1]
 [0 1]]
(102876,)
DT accuracy on test data:  0.458869156971
DT accuracy on training data:  0.457832730666


In [9]:
#try to predict gender
# dtc = DecisionTreeClassifier()
dataTrain = trainDF.drop('Gender',axis=1)
dataTrain = dataTrain.drop('Year',axis=1)
dataTrain = dataTrain.drop('Race',axis=1)
dataTrain = dataTrain.replace(['Skilled','Semi-Skilled','Unskilled'],[0,1,2])
dataTrain = dataTrain.as_matrix()

dataTest = testDF.drop('Gender',axis=1)
dataTest = dataTest.drop('Year',axis=1)
dataTest = dataTest.drop('Race',axis=1)
dataTest = dataTest.replace(['Skilled','Semi-Skilled','Unskilled'],[0,1,2])
dataTest = dataTest.as_matrix()

targetTrain = trainDF.drop('JobType',axis=1)
targetTrain = targetTrain.drop('Race',axis=1)
targetTrain = targetTrain.drop('Year',axis=1)
targetTrain = targetTrain.replace(['Men','Women'],[0,1])
targetTrain = targetTrain.as_matrix()

targetTest = testDF.drop('JobType',axis=1)
targetTest = targetTest.drop('Race',axis=1)
targetTest = targetTest.drop('Year',axis=1)
targetTest = targetTest.replace(['Men','Women'],[0,1])
targetTest = targetTest.as_matrix()

targetTest = (targetTest.ravel())
targetTrain = targetTrain.ravel()
print (dataTest)
print (targetTrain.shape)

dtc.fit(dataTrain, targetTrain)
y_pred_test = dtc.predict(dataTest)
print('DT accuracy on test data: ', dtc.score(dataTest, targetTest))
y_pred_train = dtc.predict(dataTest)
print('DT accuracy on training data: ', dtc.score(dataTrain, targetTrain))

dot_data = tree.export_graphviz(dtc,out_file='treePredictGenderNoRace.dot',feature_names=['JobType'],  
                         class_names=['Men','Women'],
                         filled=True)  

[[2]
 [0]
 [0]
 ..., 
 [1]
 [1]
 [2]]
(102876,)
DT accuracy on test data:  0.5634677631
DT accuracy on training data:  0.564407636378


In [33]:
#try to predict gender
dataTrain = trainDF.drop('Gender',axis=1)
dataTrain = dataTrain.drop('Year',axis=1)
# dataTrain = dataTrain.drop('Race',axis=1)
dataTrain = dataTrain.replace(['Skilled','Semi-Skilled','Unskilled','Minority','White'],[0,1,2,0,1])
dataTrain = dataTrain.as_matrix()

dataTest = testDF.drop('Gender',axis=1)
dataTest = dataTest.drop('Year',axis=1)
# dataTest = dataTest.drop('Race',axis=1)
dataTest = dataTest.replace(['Skilled','Semi-Skilled','Unskilled','Minority','White'],[0,1,2,0,1])
dataTest = dataTest.as_matrix()

targetTrain = trainDF.drop('JobType',axis=1)
targetTrain = targetTrain.drop('Race',axis=1)
targetTrain = targetTrain.drop('Year',axis=1)
targetTrain = targetTrain.replace(['Men','Women'],[0,1])
targetTrain = targetTrain.as_matrix()

targetTest = testDF.drop('JobType',axis=1)
targetTest = targetTest.drop('Race',axis=1)
targetTest = targetTest.drop('Year',axis=1)
targetTest = targetTest.replace(['Men','Women'],[0,1])
targetTest = targetTest.as_matrix()

targetTest = (targetTest.ravel())
targetTrain = targetTrain.ravel()
print (dataTest)
print (targetTrain.shape)

dtc.fit(dataTrain, targetTrain)
y_pred_test = dtc.predict(dataTest)
print('DT accuracy on test data: ', dtc.score(dataTest, targetTest))
y_pred_train = dtc.predict(dataTest)
print('DT accuracy on training data: ', dtc.score(dataTrain, targetTrain))

dot_data = tree.export_graphviz(dtc,out_file='treePredictGenderWithRace.dot',feature_names=['Race','JobType'],  
                         class_names=['Men','Women'],
                         filled=True)  

[[1 2]
 [1 0]
 [1 0]
 ..., 
 [1 1]
 [0 1]
 [0 2]]
(102876,)
DT accuracy on test data:  0.5634677631
DT accuracy on training data:  0.564407636378


In [14]:
#try to predict race
dataTrain = trainDF.drop('Gender',axis=1)
dataTrain = dataTrain.drop('Year',axis=1)
dataTrain = dataTrain.drop('Race',axis=1)
dataTrain = dataTrain.replace(['Skilled','Semi-Skilled','Unskilled'],[0,1,2])
dataTrain = dataTrain.as_matrix()

dataTest = testDF.drop('Gender',axis=1)
dataTest = dataTest.drop('Year',axis=1)
dataTest = dataTest.drop('Race',axis=1)
dataTest = dataTest.replace(['Skilled','Semi-Skilled','Unskilled'],[0,1,2])
dataTest = dataTest.as_matrix()

targetTrain = trainDF.drop('JobType',axis=1)
targetTrain = targetTrain.drop('Gender',axis=1)
targetTrain = targetTrain.drop('Year',axis=1)
targetTrain = targetTrain.replace(['Minority','White'],[0,1])
targetTrain = targetTrain.as_matrix()

targetTest = testDF.drop('JobType',axis=1)
targetTest = targetTest.drop('Year',axis=1)
targetTest = targetTest.drop('Gender',axis=1)
targetTest = targetTest.replace(['Minority','White'],[0,1])
targetTest = targetTest.as_matrix()

targetTest = (targetTest.ravel())
targetTrain = targetTrain.ravel()
print (dataTest)
print (targetTrain.shape)

dtc.fit(dataTrain, targetTrain)
y_pred_test = dtc.predict(dataTest)
print('DT accuracy on test data: ', dtc.score(dataTest, targetTest))
y_pred_train = dtc.predict(dataTest)
print('DT accuracy on training data: ', dtc.score(dataTrain, targetTrain))

dot_data = tree.export_graphviz(dtc,out_file='treePredictRaceByJob.dot',feature_names=['JobType'],  
                         class_names=['Minority','White'],
                         filled=True)  

[[2]
 [0]
 [0]
 ..., 
 [1]
 [1]
 [2]]
(102876,)
DT accuracy on test data:  0.617443793194
DT accuracy on training data:  0.615274699638
